### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Katharsas** [fmagin/ghidra_scripts#1]
Would you mind adding a license to this project? I would like to fork [ParseDataType.java](https://github.com/fmagin/ghidra_scripts/blob/master/ParseDataType.java), but i think i cannot legally make my changes open source unless you add a license^^

I guess i could make enough changes so that it no longer counts a derivative, but a license would be easier for me^^

**Comment by fmagin** [comment]
Good point, explicitly made this repo MIT licensed now. I appreciate your diligence!

**Comment by Katharsas** [comment]
I added ability to select target category and adding multiple structs in one dialog: https://github.com/Katharsas/ghidra-struct-importer : )

Thanks for providing some example code, its kinda hard to find more advanced examples.

**Comment by fmagin** [comment]
Adding multiple structs should have worked in my version of the script too, (just kinda implicitly and only the last one was shown IIRC). But your UI for this is definitely much nicer than what I hacked up.

I have a bit more experience with the parser logic and data type manager so if you want you can DM me on Twitter or something if you have questions. I'm also actively monitoring the `ghidra` tag and answering questions on the https://reverseengineering.stackexchange.com/

**Comment by Katharsas** [comment]
Ahh interesting! Thanks!
